// Catalog + content seed data. Products are written to the database on first boot;
// fabrics and pages are served straight from here. Each product has a studio shot (image)
// and an on-model photo (model_image), and every colour has its own pair of photos.

const products = [
  // Men's
  {
    id: 'oversized-heavyweight-tee',
    name: 'Oversized Heavyweight Tee',
    tagline: 'Tees',
    material: '7oz Garment-Dyed Cotton',
    category: 'tops',
    gender: 'men',
    price_cents: 2400,
    badge: 'Best Seller',
    image: '/images/oversized-tee.jpg',
    model_image: '/images/model-oversized-tee.jpg',
    description: 'A thick, oversized tee with dropped shoulders and a wide, boxy body. Garment-dyed for a soft, lived-in colour, with a tight ribbed collar that holds its shape.',
    colors: [
      { name: 'Bone', hex: '#e9e2d3', image: '/images/oversized-tee.jpg', modelImage: '/images/model-oversized-tee.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/oversized-tee-black.jpg', modelImage: '/images/model-oversized-tee-black.jpg' },
      { name: 'Washed Olive', hex: '#6b6a4f', image: '/images/oversized-tee-washed-olive.jpg', modelImage: '/images/model-oversized-tee-washed-olive.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 150,
  },
  {
    id: 'heavyweight-long-sleeve',
    name: 'Heavyweight Long Sleeve',
    tagline: 'Long Sleeves',
    material: '7oz Garment-Dyed Cotton',
    category: 'tops',
    gender: 'men',
    price_cents: 3200,
    badge: '',
    image: '/images/long-sleeve.jpg',
    model_image: '/images/model-long-sleeve.jpg',
    description: 'Our heavyweight tee with long sleeves and ribbed cuffs. Relaxed through the body, so it layers under a quarter-zip or works on its own.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/long-sleeve.jpg', modelImage: '/images/model-long-sleeve.jpg' },
      { name: 'Bone', hex: '#e9e2d3', image: '/images/long-sleeve-bone.jpg', modelImage: '/images/model-long-sleeve-bone.jpg' },
      { name: 'Walnut', hex: '#6b4f3a', image: '/images/long-sleeve-walnut.jpg', modelImage: '/images/model-long-sleeve-walnut.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 100,
  },
  {
    id: 'garment-dyed-pocket-tee',
    name: 'Garment-Dyed Pocket Tee',
    tagline: 'Tees',
    material: '6.1oz Garment-Dyed Cotton',
    category: 'tops',
    gender: 'men',
    price_cents: 2800,
    badge: 'New',
    image: '/images/pocket-tee.jpg',
    model_image: '/images/model-pocket-tee.jpg',
    description: 'A relaxed, garment-dyed cotton tee with a chest pocket. Washed after dyeing for a soft, broken-in feel and a slightly faded colour from day one.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/pocket-tee.jpg', modelImage: '/images/model-pocket-tee.jpg' },
      { name: 'Grey', hex: '#8d8f8f', image: '/images/pocket-tee-grey.jpg', modelImage: '/images/model-pocket-tee-grey.jpg' },
      { name: 'Navy', hex: '#1d2433', image: '/images/pocket-tee-navy.jpg', modelImage: '/images/model-pocket-tee-navy.jpg' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    stock: 120,
  },
  {
    id: 'quarter-zip-fleece',
    name: 'Quarter-Zip Fleece',
    tagline: 'Quarter-Zips',
    material: '12oz Brushed Fleece',
    category: 'layers',
    gender: 'men',
    price_cents: 5600,
    badge: 'Best Seller',
    image: '/images/quarter-zip.jpg',
    model_image: '/images/model-quarter-zip.jpg',
    description: 'The layer of the year: a heavyweight fleece quarter-zip with a stand collar and a matte metal zip. Clean enough for the office, cosy enough for the weekend.',
    colors: [
      { name: 'Sand', hex: '#cdbb98', image: '/images/quarter-zip.jpg', modelImage: '/images/model-quarter-zip.jpg' },
      { name: 'Charcoal', hex: '#37393d', image: '/images/quarter-zip-charcoal.jpg', modelImage: '/images/model-quarter-zip-charcoal.jpg' },
      { name: 'Navy', hex: '#1d2433', image: '/images/quarter-zip-navy.jpg', modelImage: '/images/model-quarter-zip-navy.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  {
    id: 'oversized-hoodie',
    name: 'Oversized Hoodie',
    tagline: 'Hoodies',
    material: '14oz Brushed Fleece',
    category: 'layers',
    gender: 'men',
    price_cents: 6000,
    badge: 'Matching Set',
    image: '/images/oversized-hoodie.jpg',
    model_image: '/images/model-oversized-hoodie.jpg',
    description: 'A heavyweight oversized hoodie with dropped shoulders, a double-lined hood and a roomy kangaroo pocket. Pair it with the Straight-Leg Sweatpant in the same colour for a matching set.',
    colors: [
      { name: 'Bark', hex: '#5e4331', image: '/images/oversized-hoodie.jpg', modelImage: '/images/model-oversized-hoodie.jpg' },
      { name: 'Charcoal', hex: '#37393d', image: '/images/oversized-hoodie-charcoal.jpg', modelImage: '/images/model-oversized-hoodie-charcoal.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/oversized-hoodie-black.jpg', modelImage: '/images/model-oversized-hoodie-black.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 100,
  },
  {
    id: 'heavyweight-crewneck',
    name: 'Heavyweight Crewneck',
    tagline: 'Sweatshirts',
    material: '14oz Brushed Fleece',
    category: 'layers',
    gender: 'men',
    price_cents: 4800,
    badge: '',
    image: '/images/crewneck.jpg',
    model_image: '/images/model-crewneck.jpg',
    description: 'A classic heavyweight crewneck sweatshirt with a relaxed fit and thick ribbed trims. The everyday sweatshirt you will wear on repeat.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98', image: '/images/crewneck.jpg', modelImage: '/images/model-crewneck.jpg' },
      { name: 'Khaki', hex: '#a69373', image: '/images/crewneck-khaki.jpg', modelImage: '/images/model-crewneck-khaki.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/crewneck-black.jpg', modelImage: '/images/model-crewneck-black.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  {
    id: 'straight-leg-sweatpant',
    name: 'Straight-Leg Sweatpant',
    tagline: 'Sweatpants',
    material: '14oz Brushed Fleece',
    category: 'bottoms',
    gender: 'men',
    price_cents: 5600,
    badge: 'Matching Set',
    image: '/images/straight-sweatpant.jpg',
    model_image: '/images/model-straight-sweatpant.jpg',
    description: 'A relaxed straight-leg sweatpant with an open hem that sits clean over sneakers. Wide drawcord waistband and deep pockets. Matches the Oversized Hoodie.',
    colors: [
      { name: 'Bark', hex: '#5e4331', image: '/images/straight-sweatpant.jpg', modelImage: '/images/model-straight-sweatpant.jpg' },
      { name: 'Charcoal', hex: '#37393d', image: '/images/straight-sweatpant-charcoal.jpg', modelImage: '/images/model-straight-sweatpant-charcoal.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/straight-sweatpant-black.jpg', modelImage: '/images/model-straight-sweatpant-black.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 100,
  },
  {
    id: 'cargo-sweatpant',
    name: 'Cargo Sweatpant',
    tagline: 'Sweatpants',
    material: '12oz Brushed Fleece',
    category: 'bottoms',
    gender: 'men',
    price_cents: 6200,
    badge: 'New',
    image: '/images/cargo-sweatpant.jpg',
    model_image: '/images/model-cargo-sweatpant.jpg',
    description: 'Heavyweight sweats with utility cargo pockets on the thighs and a relaxed straight leg. All the comfort of sweatpants with a bit more edge.',
    colors: [
      { name: 'Olive', hex: '#4d5340', image: '/images/cargo-sweatpant.jpg', modelImage: '/images/model-cargo-sweatpant.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/cargo-sweatpant-black.jpg', modelImage: '/images/model-cargo-sweatpant-black.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 80,
  },
  // Women's
  {
    id: 'fitted-baby-tee',
    name: 'Fitted Baby Tee',
    tagline: 'Tees',
    material: 'Stretch Rib Cotton',
    category: 'tops',
    gender: 'women',
    price_cents: 2200,
    badge: 'Best Seller',
    image: '/images/baby-tee.jpg',
    model_image: '/images/model-baby-tee.jpg',
    description: 'A fitted, slightly cropped baby tee in soft stretch rib. The perfect partner for wide-leg sweats, flare leggings and everything in between.',
    colors: [
      { name: 'White', hex: '#f4f2ed', image: '/images/baby-tee.jpg', modelImage: '/images/model-baby-tee.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/baby-tee-black.jpg', modelImage: '/images/model-baby-tee-black.jpg' },
      { name: 'Sand', hex: '#cdbb98', image: '/images/baby-tee-sand.jpg', modelImage: '/images/model-baby-tee-sand.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 150,
  },
  {
    id: 'fitted-long-sleeve',
    name: 'Fitted Long Sleeve',
    tagline: 'Long Sleeves',
    material: 'Stretch Rib Cotton',
    category: 'tops',
    gender: 'women',
    price_cents: 3400,
    badge: '',
    image: '/images/fitted-long-sleeve.jpg',
    model_image: '/images/model-fitted-long-sleeve.jpg',
    description: 'A slim, fitted long sleeve in soft stretch rib with a clean crew neck. Layers under everything and looks just as good on its own.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/fitted-long-sleeve.jpg', modelImage: '/images/model-fitted-long-sleeve.jpg' },
      { name: 'Bone', hex: '#e9e2d3', image: '/images/fitted-long-sleeve-bone.jpg', modelImage: '/images/model-fitted-long-sleeve-bone.jpg' },
      { name: 'Espresso', hex: '#3b2a20', image: '/images/fitted-long-sleeve-espresso.jpg', modelImage: '/images/model-fitted-long-sleeve-espresso.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 90,
  },
  {
    id: 'high-neck-racer-tank',
    name: 'High-Neck Racer Tank',
    tagline: 'Tanks',
    material: 'Soft Micro-Rib Knit',
    category: 'tops',
    gender: 'women',
    price_cents: 3200,
    badge: 'New',
    image: '/images/racer-tank.jpg',
    model_image: '/images/model-racer-tank.jpg',
    description: 'A fitted racerback tank with a modern high neckline and a longline body that skims the hips. Soft, stretchy micro rib that looks just as good tucked into trousers as it does at the gym.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/racer-tank.jpg', modelImage: '/images/model-racer-tank.jpg' },
      { name: 'White', hex: '#f4f2ed', image: '/images/racer-tank-white.jpg', modelImage: '/images/model-racer-tank-white.jpg' },
      { name: 'Heather Grey', hex: '#9a9a98', image: '/images/racer-tank-heather-grey.jpg', modelImage: '/images/model-racer-tank-heather-grey.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 120,
  },
  {
    id: 'cropped-quarter-zip',
    name: 'Cropped Quarter-Zip',
    tagline: 'Quarter-Zips',
    material: '12oz Brushed Fleece',
    category: 'layers',
    gender: 'women',
    price_cents: 5400,
    badge: 'Best Seller',
    image: '/images/cropped-quarter-zip.jpg',
    model_image: '/images/model-cropped-quarter-zip.jpg',
    description: 'A cropped fleece quarter-zip that hits right at the waist, with a stand collar and matte metal zip. Made for high-rise leggings and wide-leg sweats.',
    colors: [
      { name: 'Sand', hex: '#cdbb98', image: '/images/cropped-quarter-zip.jpg', modelImage: '/images/model-cropped-quarter-zip.jpg' },
      { name: 'Black', hex: '#111317', image: '/images/cropped-quarter-zip-black.jpg', modelImage: '/images/model-cropped-quarter-zip-black.jpg' },
      { name: 'Heather Grey', hex: '#9a9a98', image: '/images/cropped-quarter-zip-heather-grey.jpg', modelImage: '/images/model-cropped-quarter-zip-heather-grey.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 90,
  },
  {
    id: 'oversized-sweatshirt',
    name: 'Oversized Sweatshirt',
    tagline: 'Sweatshirts',
    material: '14oz Brushed Fleece',
    category: 'layers',
    gender: 'women',
    price_cents: 5000,
    badge: 'Matching Set',
    image: '/images/oversized-sweatshirt.jpg',
    model_image: '/images/model-oversized-sweatshirt.jpg',
    description: 'A slouchy oversized crewneck with dropped shoulders and long ribbed cuffs. Pair it with the Wide-Leg Sweatpant in the same colour for a matching set.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98', image: '/images/oversized-sweatshirt.jpg', modelImage: '/images/model-oversized-sweatshirt.jpg' },
      { name: 'Bone', hex: '#e9e2d3', image: '/images/oversized-sweatshirt-bone.jpg', modelImage: '/images/model-oversized-sweatshirt-bone.jpg' },
      { name: 'Sage', hex: '#9aa58c', image: '/images/oversized-sweatshirt-sage.jpg', modelImage: '/images/model-oversized-sweatshirt-sage.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 90,
  },
  {
    id: 'flare-legging',
    name: 'Flare Legging',
    tagline: 'Leggings',
    material: 'Sculpt Performance Knit',
    category: 'bottoms',
    gender: 'women',
    price_cents: 4400,
    badge: 'Best Seller',
    image: '/images/flare-legging.jpg',
    model_image: '/images/model-flare-legging.jpg',
    description: 'A high-waisted legging that hugs through the thigh and flares from the knee. Squat-proof sculpt knit with a smoothing waistband.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/flare-legging.jpg', modelImage: '/images/model-flare-legging.jpg' },
      { name: 'Espresso', hex: '#3b2a20', image: '/images/flare-legging-espresso.jpg', modelImage: '/images/model-flare-legging-espresso.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 120,
  },
  {
    id: 'wide-leg-sweatpant',
    name: 'Wide-Leg Sweatpant',
    tagline: 'Sweatpants',
    material: '14oz Brushed Fleece',
    category: 'bottoms',
    gender: 'women',
    price_cents: 5600,
    badge: 'Matching Set',
    image: '/images/wide-leg-sweatpant.jpg',
    model_image: '/images/model-wide-leg-sweatpant.jpg',
    description: 'A high-waisted sweatpant with a wide, straight leg that pools just right over sneakers. Matches the Oversized Sweatshirt.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98', image: '/images/wide-leg-sweatpant.jpg', modelImage: '/images/model-wide-leg-sweatpant.jpg' },
      { name: 'Bone', hex: '#e9e2d3', image: '/images/wide-leg-sweatpant-bone.jpg', modelImage: '/images/model-wide-leg-sweatpant-bone.jpg' },
      { name: 'Sage', hex: '#9aa58c', image: '/images/wide-leg-sweatpant-sage.jpg', modelImage: '/images/model-wide-leg-sweatpant-sage.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 90,
  },
  {
    id: 'side-stripe-track-pant',
    name: 'Side-Stripe Track Pant',
    tagline: 'Track Pants',
    material: 'Water-Resistant Shell',
    category: 'bottoms',
    gender: 'women',
    price_cents: 4800,
    badge: 'New',
    image: '/images/track-pant.jpg',
    model_image: '/images/model-track-pant.jpg',
    description: 'A lightweight track pant with a cream stripe down each leg, a soft mesh lining and elastic cuffs that show off your sneakers. Sporty enough for a run, sharp enough with a tank and a blazer.',
    colors: [
      { name: 'Black', hex: '#111317', image: '/images/track-pant.jpg', modelImage: '/images/model-track-pant.jpg' },
      { name: 'Navy', hex: '#1d2433', image: '/images/track-pant-navy.jpg', modelImage: '/images/model-track-pant-navy.jpg' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 100,
  },
];

const fabrics = [
  {
    id: 'heavyweight-cotton',
    specimen: 'VEYA-TX-2201',
    metric: 'WEIGHT: 7 OZ / PRE-SHRUNK',
    focusTitle: 'Dense Garment-Dyed Cotton',
    focusText: 'A tight knit that keeps tees from twisting or shrinking, dyed after sewing for a soft, lived-in colour.',
  },
  {
    id: 'brushed-fleece',
    specimen: 'VEYA-TX-4417',
    metric: 'WEIGHT: 12–14 OZ / BRUSHED BACK',
    focusTitle: 'Heavyweight Brushed Fleece',
    focusText: 'Thick cotton fleece brushed on the inside for warmth, with a smooth face that resists pilling.',
  },
  {
    id: 'sculpt-knit',
    specimen: 'VEYA-TX-7731',
    metric: 'STRETCH: 4-WAY / SQUAT-PROOF',
    focusTitle: 'Sculpt Performance Knit',
    focusText: 'A smooth, buttery knit that holds you in, wicks sweat and never goes see-through.',
  },
];

const pages = {
  shipping: {
    title: 'Shipping & Returns',
    kicker: 'HELP',
    body: [
      'Every piece is made to order just for you, then shipped. Most orders are made in 2–4 business days and arrive 3–7 business days after that.',
      'Shipping is $6, and free on orders over $75. You will get a tracking link by email as soon as your order ships.',
      'Wrong size? We offer free exchanges within 30 days of delivery. Because items are made to order, we can only refund items that arrive damaged or with a printing or manufacturing fault. Contact us within 30 days with a photo and we will make it right.',
    ],
  },
  'size-guide': {
    title: 'Size Guide',
    kicker: 'HELP',
    body: [
      'Tops and layers are a relaxed fit. Size down for a closer fit, or stay true to size for the intended boxy look.',
      'Chest (body width × 2): XS 38" · S 40" · M 44" · L 48" · XL 52" · 2XL 56".',
      'Body length: XS 27" · S 28" · M 29" · L 30" · XL 31" · 2XL 32".',
      'Men\'s tops and layers are an oversized, relaxed fit. Women\'s baby tees, tanks and long sleeves are fitted; sweatshirts are oversized.',
      'Sweatpants and track pants have elastic drawcord waists and run true to size. Leggings are compressive: size up if you are between sizes.',
    ],
  },
  'lab-documentation': {
    title: 'Fabrics & Care',
    kicker: 'THE FABRICS',
    body: [
      'Heavyweight Cotton: 7oz combed cotton, pre-shrunk and garment-dyed so it keeps its size and colour. Wash cold inside out, tumble dry low.',
      'Brushed Fleece: 12–14oz cotton fleece, brushed inside for warmth. Wash cold inside out with similar colours and tumble dry low to keep it soft.',
      'Sculpt Knit: four-way-stretch performance knit for our flare leggings. Wash cold, skip fabric softener and hang dry to keep its shape.',
      'Printed pieces: wash inside out and avoid ironing directly on the print.',
    ],
  },
  sustainability: {
    title: 'Our Approach',
    kicker: 'ABOUT VEYA',
    body: [
      'Everything is made to order. Nothing is produced until you buy it, so there is no overstock to burn or bin.',
      'We use OEKO-TEX certified cotton and keep our colours to a small, earthy palette that mixes and matches.',
      'Fewer, better basics: a small range of everyday pieces we keep improving instead of chasing trends.',
      'Built with the people who wear it: members of the VEYA Collective get new drops first and vote on what we make next.',
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    kicker: 'HELP',
    body: [
      'We collect only what we need to fulfil orders and run your account: your name, email, shipping address and order history.',
      'Passwords are stored as salted scrypt hashes. Payment details are handled by our checkout provider and never stored on our servers.',
      'Marketing emails only go to people who sign up, and you can unsubscribe at any time.',
    ],
  },
};

// Ids of products taken out of the range; older databases drop them on boot.
const retiredProductIds = [
  'heavyweight-boxy-tee', 'heavyweight-hoodie', 'heavyweight-zip-hoodie', 'coach-jacket',
  'heavyweight-sweatpants', 'camp-collar-shirt', 'everyday-crew', 'half-zip-pullover',
  'everyday-jogger', 'linen-short', 'relaxed-sweatpant', 'tech-jogger', 'fleece-short',
  'cropped-boxy-tee', 'ribbed-tank', 'cropped-hoodie', 'oversized-zip-hoodie',
  'relaxed-oxford-shirt', 'sculpt-sports-bra', 'biker-short', 'micro-rib-tank', 'sweat-short',
];

module.exports = { products, fabrics, pages, retiredProductIds };
