// Catalog + content seed data. Products are written to the database on first boot;
// fabrics and pages are served straight from here. Each product has a studio shot (image)
// and an on-model photo (model_image).

const products = [
  {
    id: 'heavyweight-boxy-tee',
    name: 'Heavyweight Boxy Tee',
    tagline: 'Tees',
    material: '6.5oz Combed Cotton',
    category: 'tops',
    gender: 'men',
    price_cents: 2200,
    badge: 'Best Seller',
    image: '/images/tee.jpg',
    model_image: '/images/model-tee.jpg',
    description: 'A boxy heavyweight tee with a dropped shoulder and a ribbed collar that keeps its shape. Thick enough that it never goes see-through, soft from the first wear.',
    colors: [
      { name: 'Off-White', hex: '#ece8df' },
      { name: 'Black', hex: '#111317' },
      { name: 'Washed Grey', hex: '#4a4b4d' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 150,
  },
  {
    id: 'heavyweight-hoodie',
    name: 'Heavyweight Hoodie',
    tagline: 'Hoodies',
    material: '14oz Cotton Fleece',
    category: 'layers',
    gender: 'men',
    price_cents: 5800,
    badge: 'Best Seller',
    image: '/images/hoodie.jpg',
    model_image: '/images/model-hoodie.jpg',
    description: 'A heavyweight brushed-fleece hoodie with a double-lined hood and a roomy kangaroo pocket. Relaxed through the body and built to survive a lot of washes.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 100,
  },
  {
    id: 'coach-jacket',
    name: 'Coach Jacket',
    tagline: 'Jackets',
    material: 'Water-Resistant Nylon',
    category: 'layers',
    gender: 'men',
    price_cents: 7800,
    badge: 'New',
    image: '/images/coach-jacket.jpg',
    model_image: '/images/model-coach-jacket.jpg',
    description: 'A lightweight nylon coach jacket with snap buttons, a corduroy collar and a soft mesh lining. Water-resistant, packable and easy to throw over anything.',
    colors: [
      { name: 'Black', hex: '#111317' },
      { name: 'Olive', hex: '#4d5340' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 60,
  },
  {
    id: 'heavyweight-sweatpants',
    name: 'Heavyweight Sweatpants',
    tagline: 'Sweatpants',
    material: '10oz Brushed Fleece',
    category: 'bottoms',
    gender: 'women',
    price_cents: 5800,
    badge: 'Best Seller',
    image: '/images/sweatpants.jpg',
    model_image: '/images/model-sweatpants.jpg',
    description: 'Classic heavyweight sweatpants in thick, brushed-back fleece with a roomy, relaxed fit. Deep side pockets, an interior drawcord and elastic cuffs make them the pair you live in all weekend.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 80,
  },
  {
    id: 'camp-collar-shirt',
    name: 'Camp Collar Shirt',
    tagline: 'Shirts',
    material: 'Cotton-Linen Blend',
    category: 'tops',
    gender: 'men',
    price_cents: 4200,
    badge: 'New',
    image: '/images/camp-shirt.jpg',
    model_image: '/images/model-camp-shirt.jpg',
    description: 'An airy camp-collar shirt in cotton-linen with a relaxed, boxy fit. Wear it open over a tee on hot days or buttoned up for dinner.',
    colors: [
      { name: 'Cream', hex: '#ece5d3' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 80,
  },
  {
    id: 'everyday-crew',
    name: 'Everyday Crew',
    tagline: 'Sweaters',
    material: 'Soft Cotton Knit',
    category: 'tops',
    gender: 'women',
    price_cents: 4800,
    badge: '',
    image: '/images/cotton-crew.jpg',
    model_image: '/images/model-crew.jpg',
    description: 'A soft cotton crew neck that works on its own or under a jacket. Easy to wash, no itch, and smart enough for the office.',
    colors: [
      { name: 'Oatmeal', hex: '#b9ab95' },
      { name: 'Charcoal', hex: '#37393d' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 70,
  },
  {
    id: 'half-zip-pullover',
    name: 'Half-Zip Pullover',
    tagline: 'Activewear',
    material: 'Brushed Technical Jersey',
    category: 'layers',
    gender: 'men',
    price_cents: 5200,
    badge: '',
    image: '/images/half-zip.jpg',
    model_image: '/images/model-half-zip.jpg',
    description: 'A brushed half-zip for workouts, walks and everything after. Breathable, quick-drying and clean enough to keep on all day.',
    colors: [
      { name: 'Black', hex: '#111317' },
      { name: 'Graphite', hex: '#37393d' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 75,
  },
  {
    id: 'everyday-jogger',
    name: 'Everyday Jogger',
    tagline: 'Joggers',
    material: 'Recycled Stretch Knit',
    category: 'bottoms',
    gender: 'women',
    price_cents: 6800,
    badge: 'New',
    image: '/images/jogger.jpg',
    model_image: '/images/model-jogger.jpg',
    description: 'A sleek, slim-tapered jogger in a smooth stretch knit that is soft on the outside and even softer inside. Polished enough for the office, comfortable enough for the gym, with an elastic drawcord waist, side pockets and tapered cuffs.',
    colors: [
      { name: 'Black', hex: '#111317' },
      { name: 'Navy', hex: '#1d2433' },
      { name: 'Graphite', hex: '#37393d' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  {
    id: 'linen-short',
    name: 'Linen Short',
    tagline: 'Shorts',
    material: 'Washed Linen',
    category: 'bottoms',
    gender: 'women',
    price_cents: 3800,
    badge: 'New',
    image: '/images/linen-short.jpg',
    model_image: '/images/model-linen-short.jpg',
    description: 'Washed linen shorts with a drawstring waist and a 5-inch inseam. Cool, breathable and easy to dress up or down all summer.',
    colors: [
      { name: 'Sand', hex: '#cdbb98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  // Men's
  {
    id: 'relaxed-sweatpant',
    name: 'Relaxed Sweatpant',
    tagline: 'Sweatpants',
    material: '12oz Cotton Fleece',
    category: 'bottoms',
    gender: 'men',
    price_cents: 5800,
    badge: 'New',
    image: '/images/relaxed-sweatpant.jpg',
    model_image: '/images/model-relaxed-sweatpant.jpg',
    description: 'A heavyweight fleece sweatpant with a relaxed straight leg and an open hem that sits clean over sneakers. Wide drawcord waistband, deep side pockets, brushed inside.',
    colors: [
      { name: 'Charcoal', hex: '#37393d' },
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    stock: 80,
  },
  {
    id: 'tech-jogger',
    name: 'Tech Jogger',
    tagline: 'Joggers',
    material: '4-Way Stretch Twill',
    category: 'bottoms',
    gender: 'men',
    price_cents: 6800,
    badge: 'Best Seller',
    image: '/images/tech-jogger.jpg',
    model_image: '/images/model-tech-jogger.jpg',
    description: 'A tapered commuter jogger in a smooth four-way-stretch fabric. Zip side pockets keep your phone put, and the slim cuffed leg looks sharp from the train to the gym.',
    colors: [
      { name: 'Navy', hex: '#1d2433' },
      { name: 'Black', hex: '#111317' },
      { name: 'Graphite', hex: '#37393d' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  {
    id: 'fleece-short',
    name: 'Fleece Short',
    tagline: 'Shorts',
    material: '10oz Cotton Fleece',
    category: 'bottoms',
    gender: 'men',
    price_cents: 3600,
    badge: '',
    image: '/images/fleece-short.jpg',
    model_image: '/images/model-fleece-short.jpg',
    description: 'A heavyweight fleece short with a 7-inch inseam, a drawcord waist and deep side pockets. The warm-weather version of your favourite sweats.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['S', 'M', 'L', 'XL', '2XL'],
    stock: 90,
  },
  // Women's
  {
    id: 'cropped-boxy-tee',
    name: 'Cropped Boxy Tee',
    tagline: 'Tees',
    material: '6.5oz Combed Cotton',
    category: 'tops',
    gender: 'women',
    price_cents: 2400,
    badge: 'New',
    image: '/images/cropped-tee.jpg',
    model_image: '/images/model-cropped-tee.jpg',
    description: 'Our heavyweight tee, cut boxy and cropped to hit right at the waist. Perfect with high-rise joggers or trousers, and thick enough that it never goes see-through.',
    colors: [
      { name: 'Off-White', hex: '#ece8df' },
      { name: 'Black', hex: '#111317' },
      { name: 'Heather Grey', hex: '#9a9a98' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 120,
  },
  {
    id: 'ribbed-tank',
    name: 'Ribbed Tank',
    tagline: 'Tanks',
    material: 'Stretch Rib Cotton',
    category: 'tops',
    gender: 'women',
    price_cents: 2000,
    badge: '',
    image: '/images/ribbed-tank.jpg',
    model_image: '/images/model-ribbed-tank.jpg',
    description: 'A fitted scoop-neck tank in a soft stretch rib. Wear it alone in summer or layer it under a zip hoodie the rest of the year.',
    colors: [
      { name: 'Black', hex: '#111317' },
      { name: 'White', hex: '#f4f2ed' },
      { name: 'Oatmeal', hex: '#b9ab95' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 120,
  },
  {
    id: 'cropped-hoodie',
    name: 'Cropped Hoodie',
    tagline: 'Hoodies',
    material: '12oz Cotton Fleece',
    category: 'layers',
    gender: 'women',
    price_cents: 5400,
    badge: 'Best Seller',
    image: '/images/cropped-hoodie.jpg',
    model_image: '/images/model-cropped-hoodie.jpg',
    description: 'A boxy cropped hoodie in heavyweight brushed fleece, with a ribbed hem that sits at the waist. Made for high-rise joggers and lazy Sundays.',
    colors: [
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
      { name: 'Cream', hex: '#e8e0cf' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 80,
  },
  {
    id: 'oversized-zip-hoodie',
    name: 'Oversized Zip Hoodie',
    tagline: 'Hoodies',
    material: '14oz Cotton Fleece',
    category: 'layers',
    gender: 'women',
    price_cents: 6200,
    badge: 'New',
    image: '/images/zip-hoodie.jpg',
    model_image: '/images/model-zip-hoodie.jpg',
    description: 'An oversized full-zip hoodie with dropped shoulders, a metal zip and roomy pockets. The cosy layer you will reach for every single morning.',
    colors: [
      { name: 'Oatmeal', hex: '#d9cdb8' },
      { name: 'Heather Grey', hex: '#9a9a98' },
      { name: 'Black', hex: '#111317' },
    ],
    sizes: ['XS', 'S', 'M', 'L', 'XL'],
    stock: 70,
  },
];

const fabrics = [
  {
    id: 'heavyweight-cotton',
    specimen: 'VEYA-TX-2201',
    metric: 'WEIGHT: 6.5 OZ / PRE-SHRUNK',
    focusTitle: 'Dense Combed Cotton',
    focusText: 'A tight knit that keeps tees and hoodies from twisting or shrinking in the wash.',
  },
  {
    id: 'city-shell',
    specimen: 'VEYA-TX-4417',
    metric: 'WATER RESISTANCE: LIGHT RAIN',
    focusTitle: 'Ripstop Nylon Weave',
    focusText: 'Light, packable and water-resistant enough for a sudden downpour.',
  },
  {
    id: 'washed-linen',
    specimen: 'VEYA-TX-7731',
    metric: 'AIRFLOW: 2X STANDARD COTTON',
    focusTitle: 'Open Linen Weave',
    focusText: 'Stone-washed so it starts soft and stays cool in heat and humidity.',
  },
];

const pages = {
  shipping: {
    title: 'Shipping & Returns',
    kicker: 'HELP',
    body: [
      'Every piece is made to order just for you, then shipped. Most orders are made in 2–4 business days and arrive 3–7 business days after that.',
      'Shipping is $6, and free on orders over $75. You will get a tracking link by email as soon as your order ships.',
      'Wrong size? We offer free exchanges within 30 days of delivery. Because items are made to order, we can only refund items that arrive damaged or with a printing or manufacturing fault. Contact us within 30 days with a photo and we will make it right.',
    ],
  },
  'size-guide': {
    title: 'Size Guide',
    kicker: 'HELP',
    body: [
      'Tops and layers are a relaxed fit. Size down for a closer fit, or stay true to size for the intended boxy look.',
      'Chest (body width × 2): XS 38" · S 40" · M 44" · L 48" · XL 52" · 2XL 56".',
      'Body length: XS 27" · S 28" · M 29" · L 30" · XL 31" · 2XL 32".',
      'Joggers, sweatpants and shorts have elastic drawcord waists and run true to size. Size up for a roomier fit in the sweatpants.',
    ],
  },
  'lab-documentation': {
    title: 'Fabrics & Care',
    kicker: 'THE FABRICS',
    body: [
      'Heavyweight Cotton: 6.5oz combed cotton, pre-shrunk and garment-dyed so it keeps its size and colour. Wash cold inside out, tumble dry low.',
      'Ripstop Nylon: lightweight, packable and water-resistant. Machine wash cold on a gentle cycle and hang dry.',
      'Washed Linen: open-weave linen, stone-washed for softness, with roughly twice the airflow of standard cotton. Wash cold and hang dry; a few wrinkles are part of the look.',
      'Printed pieces: wash inside out and avoid ironing directly on the print.',
    ],
  },
  sustainability: {
    title: 'Our Approach',
    kicker: 'ABOUT VEYA',
    body: [
      'Everything is made to order. Nothing is produced until you buy it, so there is no overstock to burn or bin.',
      'We use OEKO-TEX certified cotton and fluorine-free water-resistant finishes.',
      'Fewer, better basics: a small range of everyday pieces we keep improving instead of chasing trends.',
    ],
  },
  privacy: {
    title: 'Privacy Policy',
    kicker: 'HELP',
    body: [
      'We collect only what we need to fulfil orders and run your account: your name, email, shipping address and order history.',
      'Passwords are stored as salted scrypt hashes. Payment details are handled by our checkout provider and never stored on our servers.',
      'Marketing emails only go to people who sign up, and you can unsubscribe at any time.',
    ],
  },
};

module.exports = { products, fabrics, pages };
