// Theme tokens exported from the Stitch design ("Technical Luxury Atelier").
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/**/*.html', './public/**/*.js'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#c8c6c2",
        "on-error-container": "#ffdad6",
        "inverse-on-surface": "#2f3034",
        "primary": "#ffffff",
        "error": "#ffb4ab",
        "primary-container": "#e4e2dd",
        "surface-container-high": "#282a2d",
        "surface": "#111317",
        "on-primary": "#30312e",
        "surface-dim": "#111317",
        "on-background": "#e2e2e6",
        "on-primary-container": "#656461",
        "secondary-container": "#6c4200",
        "surface-variant": "#333538",
        "surface-container-low": "#1a1c1f",
        "on-tertiary-fixed": "#0c1d28",
        "tertiary": "#ffffff",
        "inverse-surface": "#e2e2e6",
        "error-container": "#93000a",
        "surface-container-highest": "#333538",
        "secondary-fixed-dim": "#f9bb72",
        "secondary": "#f9bb72",
        "on-error": "#690005",
        "primary-fixed-dim": "#c8c6c2",
        "background": "#111317",
        "on-tertiary-container": "#566674",
        "surface-bright": "#37393d",
        "inverse-primary": "#5f5e5b",
        "on-tertiary-fixed-variant": "#384955",
        "on-secondary-fixed-variant": "#663e00",
        "tertiary-container": "#d3e5f4",
        "primary-fixed": "#e4e2dd",
        "on-primary-fixed": "#1b1c19",
        "outline-variant": "#464742",
        "surface-container": "#1e2023",
        "tertiary-fixed": "#d3e5f4",
        "on-surface": "#e2e2e6",
        "secondary-fixed": "#ffddb9",
        "on-secondary": "#472a00",
        "on-surface-variant": "#c7c7bf",
        "on-primary-fixed-variant": "#474744",
        "on-tertiary": "#22323e",
        "on-secondary-fixed": "#2b1700",
        "outline": "#90918a",
        "surface-container-lowest": "#0c0e11",
        "on-secondary-container": "#edb068",
        "tertiary-fixed-dim": "#b7c9d8"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.375rem",
        "margin-mobile": "1.25rem",
        "margin-tablet": "2rem",
        "space-xl": "4rem",
        "margin": "4rem",
        "space-sm": "0.75rem",
        "space-md": "1.5rem",
        "space-lg": "2.5rem"
      },
      "fontFamily": {
        "body-lg": ["Hanken Grotesk"],
        "display-mobile": ["Bodoni Moda"],
        "headline-sm": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Bodoni Moda"],
        "display": ["Bodoni Moda"],
        "body-sm": ["Hanken Grotesk"],
        "label-lg": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Bodoni Moda"],
        "label-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-sm": ["9px", { "lineHeight": "12px", "letterSpacing": "0.14em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "display": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "label-lg": ["13px", { "lineHeight": "18px", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "label-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
