// Theme tokens: cream base with navy secondary (adapted from the Stitch "Technical Luxury Atelier" design).
/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./public/**/*.html', './public/**/*.js'],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-tint": "#34507A",
        "on-error-container": "#410E0B",
        "inverse-on-surface": "#F5EFE4",
        "primary": "#1B2A41",
        "error": "#B3261E",
        "primary-container": "#2B3D5A",
        "surface-container-high": "#E2D8C6",
        "surface": "#F5EFE4",
        "on-primary": "#F5EFE4",
        "surface-dim": "#E9E0D1",
        "on-background": "#1B2A41",
        "on-primary-container": "#DCE3EE",
        "secondary-container": "#D6DEEA",
        "surface-variant": "#E2D8C6",
        "surface-container-low": "#EFE7DA",
        "on-tertiary-fixed": "#0C1D28",
        "tertiary": "#1B2A41",
        "inverse-surface": "#1B2A41",
        "error-container": "#F9DEDC",
        "surface-container-highest": "#D8CDB9",
        "secondary-fixed-dim": "#9FB3D1",
        "secondary": "#34507A",
        "on-error": "#FFFFFF",
        "primary-fixed-dim": "#9FB3D1",
        "background": "#F5EFE4",
        "on-tertiary-container": "#DCE3EE",
        "surface-bright": "#FBF8F2",
        "inverse-primary": "#9FB3D1",
        "on-tertiary-fixed-variant": "#2B3D5A",
        "on-secondary-fixed-variant": "#2B3D5A",
        "tertiary-container": "#2B3D5A",
        "primary-fixed": "#DCE3EE",
        "on-primary-fixed": "#0F1A2B",
        "outline-variant": "#CFC5B2",
        "surface-container": "#E9E0D1",
        "tertiary-fixed": "#DCE3EE",
        "on-surface": "#1B2A41",
        "secondary-fixed": "#D6DEEA",
        "on-secondary": "#F5EFE4",
        "on-surface-variant": "#4A5568",
        "on-primary-fixed-variant": "#2B3D5A",
        "on-tertiary": "#F5EFE4",
        "on-secondary-fixed": "#0F1A2B",
        "outline": "#7D8594",
        "surface-container-lowest": "#FBF8F2",
        "on-secondary-container": "#1B2A41",
        "tertiary-fixed-dim": "#9FB3D1"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.375rem",
        "margin-mobile": "1.25rem",
        "margin-tablet": "2rem",
        "space-xl": "4rem",
        "margin": "4rem",
        "space-sm": "0.75rem",
        "space-md": "1.5rem",
        "space-lg": "2.5rem"
      },
      "fontFamily": {
        "body-lg": ["Hanken Grotesk"],
        "display-mobile": ["Bodoni Moda"],
        "headline-sm": ["Hanken Grotesk"],
        "label-sm": ["JetBrains Mono"],
        "body-md": ["Hanken Grotesk"],
        "headline-lg-mobile": ["Bodoni Moda"],
        "display": ["Bodoni Moda"],
        "body-sm": ["Hanken Grotesk"],
        "label-lg": ["JetBrains Mono"],
        "headline-md": ["Hanken Grotesk"],
        "headline-lg": ["Bodoni Moda"],
        "label-md": ["JetBrains Mono"]
      },
      "fontSize": {
        "body-lg": ["16px", { "lineHeight": "26px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "display-mobile": ["38px", { "lineHeight": "44px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "24px", "letterSpacing": "0em", "fontWeight": "600" }],
        "label-sm": ["9px", { "lineHeight": "12px", "letterSpacing": "0.14em", "fontWeight": "500" }],
        "body-md": ["14px", { "lineHeight": "22px", "letterSpacing": "0.01em", "fontWeight": "400" }],
        "headline-lg-mobile": ["30px", { "lineHeight": "36px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "display": ["56px", { "lineHeight": "64px", "letterSpacing": "-0.02em", "fontWeight": "400" }],
        "body-sm": ["12px", { "lineHeight": "18px", "letterSpacing": "0.02em", "fontWeight": "400" }],
        "label-lg": ["13px", { "lineHeight": "18px", "letterSpacing": "0.08em", "fontWeight": "500" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "500" }],
        "headline-lg": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.015em", "fontWeight": "400" }],
        "label-md": ["11px", { "lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "400" }]
      }
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
};
